Jcn 225 crear package export
janis-commerce/export pull request #1
Opened 2020-01-24 21:11 UTC by gastonpereyra

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-225

https://fizzmod.atlassian.net/browse/JCN-226
https://fizzmod.atlassian.net/browse/JCN-227
https://fizzmod.atlassian.net/browse/JCN-228

**DESCRIPCIÓN DEL REQUERIMIENTO**

Crear el package `@janiscommerce/export`.

El package debe realizar las siguientes acciones.

* Clase `ApiExport`
* Clase `CreatedListener`
* Clase `ProcessedListener`
* Clase `ControllerExport`

**DESCRIPCIÓN DE LA SOLUCIÓN**
Se desarrollaron los requerimientos solicitados

2020-01-27 18:38 UTC, Nataniel4 commented on CHANGELOG.md
>  ## [Unreleased]
Falta el `###Added`

2020-01-27 19:38 UTC, Nataniel4 commented on lib/api-export-validator.js
> +			return this._getModelInstance(controllerPath);
Si el método `_getModelInstance` se va a utilizar tambien para obtener controllers, debería tener otro nombre o utilizar otro método para los controladores.

2020-01-27 20:16 UTC, Nataniel4 commented on lib/created-listener.js
> +	async postSaveHook(exportDocumentSaved) {
Este metodo hace lo mismo que `preProcess` pero despues de guardar, lo ideal seria que o bien este metodo se llame `postProcess` o que el `preProcess` se llame `preSaveHook`, para mantener un estandar de nombres

2020-01-27 20:20 UTC, Nataniel4 commented on lib/api-export-validator.js
> +const filterStruct = struct('string | number | array');
Este archivo podria importar los structs desde `lib/helpers/structs.js`?

2020-01-27 20:26 UTC, Nataniel4 commented on lib/processed-listener.js
> +		if(!exportDocument) {
```suggestion
		if(!exportDocument || !exportDocument.files) {
			logger.info(`No document or files to export with ID: ${this.eventId} was found.`);
			return;
		}
```
Se pueden unificar los dos `if`

2020-01-27 20:46 UTC, Nataniel4 commented on README.md
> +This package will provied an API, and two Listeners to quick config a generic **EXPORT API** in yout Microservice.
Errores minimos de tipeo :policeman:

2020-01-27 20:48 UTC, Nataniel4 requested changes
Comentarios en el PR!

2020-01-28 15:53 UTC, Nataniel4 commented on README.md
> +* Configure Schemas and Serverless functions
Seria bueno aclarar que tambien hay que agregar los eventos que se emiten y los listeners para poder escucharlos.
`events/events.yml`
```yaml
- entity: export
  event: created
  hasClient: true
  hasId: true
  description: When an export was created

- entity: export
  event: processed
  hasClient: true
  hasId: true
  description: When an export was processed
```
`events/{service}/{entity}/created.yml`
```yaml
- service: {service}
  entity: export
  event: created
  listeners:
    - namespace: export
      method: created-listener
```
`events/{service}/{entity}/processed.yml`
```yaml
- service: {service}
  entity: export
  event: processed
  listeners:
    - namespace: export
      method: processed-listener
```

2020-01-28 18:50 UTC, Nataniel4 approved these changes

2020-02-06 18:48 UTC, jormaechea requested changes

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +  async formatByPage(items) {
```suggestion
  async format(item) {
```

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +  get pageLimit() {
Por acá se super bardeó la indentación..

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +  Params: `exportDocument`, the export options.
```suggestion
  Params: `exportDocumentSaved`, the export options.
```

Por otro lado, no se entiende bien qué llega en esos params.. Ni la diferencia entre el de pre contra el de post..

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +		return EventEmitter.emit({
Por acá también se bardeó la indentación..

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +    })
```suggestion
    });
```

2020-02-06 18:48 UTC, jormaechea commented on README.md
> +    })
```suggestion
    });
```

2020-02-06 18:48 UTC, jormaechea commented on docs/schemas/export/base.yml
> +      example:
Pasate los examples a cada prop, así se ve bien en la docu..

2020-02-06 18:48 UTC, jormaechea commented on docs/schemas/export/post.yml
> +          ApiSecret: []
Acá no necesita también el `JanisClient: []`?

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export-validator.js
> +		const Model = require(classPath);
```suggestion
		const TheClass = require(classPath);
```
O algo así. No es un model, lo usas para instanciar el controller también.

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export.js
> +		/* istanbul ignore else */
Tibio

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export.js
> +		try {
Un try/catch que throwea todo lo que llega, pero que invento tan útil.. :joy: 

![Image](https://i.ytimg.com/vi/kaii8ZIKpXc/hqdefault.jpg)

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export.js
> +			if(!response.body || !response.body.email)
```suggestion
			return response.body && response.body.email;
```

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +const bucket = `janis-${process.env.JANIS_SERVICE_NAME}-service-${process.env.JANIS_ENV}`;
Esto pondría en el README que tienen que estar definidas para que funcione el package..

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +const author = 'Janis';
```suggestion
const author = 'JANIS';
```

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +const author = 'Janis';
La marca es con mayus

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export.js
> +			if(error.name !== ApiSaveError.name || error.code !== ApiSaveError.codes.INVALID_ENTITY)
Tal como charlamos, hagamos que el MS tenga que implementar el modelo, y saquemos este try/catch de acá.

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +	async getItemByPage(page) {
```suggestion
	async getItemsByPage(page) {
```

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		this.filePages = Math.ceil(this.fileLimit / this.pageLimit);
```suggestion
		this.pagesPerFile = Math.ceil(this.fileLimit / this.pageLimit);
```
Queda más claro qué contiene

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		this.fileParts = Math.ceil(this.totalPages / this.filePages);
```suggestion
		this.filesQuantity = Math.ceil(this.totalPages / this.filePages);
```
También queda un poco más claro así.

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		return this.formatByFile(items.reduce((acum, item) => [...acum, ...item], []));
```suggestion
		return this.formatByFile(items.reduce((acum, page) => [...acum, ...page], []));
```

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		workbook.modified = new Date();
Es requerido settear este `modified`? Sino no le veo sentido..

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		const formattedItems = await Promise.all(items.map(item => this.format(item)));
No definiría el método `format()` en esta clase base, y chequería con `if(this.format)` antes de recorrer todos los items, y generar promises para al final de cuentas tener lo mismo que tenía si no recorría todos los items..

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		const headers = [];
En lugar de guardar todo (que te genera potencialmente un array de miles y miles de elementos (recontra repetidos), y después hacer el destructuring en el `Set`, podés directamente hacer asi:

```js
const headers = new Set();

dataset.forEach(data => {
	Object.keys(data).forEach(field => headers.add(field));
});

if(this.excludeFields && this.excludeFields.length) 
	this.excludeFields.forEach(exclude => headers.delete(exclude));

return [...headers];
```

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		const filename = `exports/${this.session.clientCode}/${this.userCreated}/${this.entity}-part${partNumber}.xlsx`;
Ojo! Es `this.userId` !!

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		return filenames.reduce((filesToSend, filename, index) => {
Esto lo cambiaría por algo así:
```js
return filenames.map(filename => `https://s3.amazonaws.com/${bucket}/${filename}`);
```

Y donde lo usás (que es para mandar el mail), haría algo como

```js
const dataToSend = {
	files: controller.getFilesPaths(files)
};
```

De esa manera queda más prolijo, y te asegurás que entregás los archivos en orden (recordá que las props de los objetos no tienen orden).
Y de paso, el día de mañana podés agregar otra data al mail sin que quede todo mezclado en el root del objeto de la data.

2020-02-06 18:48 UTC, jormaechea commented on lib/controller-export.js
> +		return filenames.reduce((filesToSend, filename, index) => {
**IMPORTANTE**: Tenemos un temita con el hecho de que el bucket no es público, con lo cual no se puede abrir el archivo con el link así nomás. Por suerte, el package de @janiscommerce/s3 tiene un método `getSignedUrl()` que te devuelve una URL con algunos parámetros, que da un acceso temporal para una operación en particular (en este caso, gettear el archivo).

Asique finalmente debería quedar algo así:
```js
return Promise.all(filenames.map(filename => s3.getSignedUrl('getObject', {
	Bucket: bucket,
	Key: filename,
	Expires: this.fileUrlExpirationTime // Configurable, con un default de 1 día (en segundos)
})));
```

Y del otro lado vas a tener que awaitearlo.

Chequeá que funque, pero debería ser algo así.

2020-02-06 18:48 UTC, jormaechea commented on lib/created-listener.js
> +     * Do somenthing before Start processing Data
```suggestion
     * Do something before Start processing Data
```

2020-02-06 18:48 UTC, jormaechea commented on lib/created-listener.js
> +     *
Quedó rara la indentación acá

2020-02-06 18:48 UTC, jormaechea commented on lib/created-listener.js
> +		await this.preSaveHook(exportDocument);
Seguro que `preSaveHook` es el mejor nombre? Todo indica que no..

2020-02-06 18:48 UTC, jormaechea commented on lib/created-listener.js
> +		await this.preSaveHook(exportDocument);
Es más como un `preProcess`, o algo asi.. O de últimas, que realmente se ejecute justo antes del save, no antes de procesar todo..

**Edit** Ahí vi el comentario viejo de Nata.. Hubiera elegido `preProcess` y `postProcess`..

2020-02-06 18:48 UTC, jormaechea commented on lib/helpers/event-emitters.js
> +const makeExportEvent = (event, id, client) => EventEmitter.emit({
Más que `makeExportEvent` se podría llamar `emitExportEvent` por lo que hace..

2020-02-06 18:48 UTC, jormaechea commented on lib/helpers/structs.js
> +const filterStruct = struct('string | number | array');
Habría que agregar booleans tambien..

2020-02-06 18:48 UTC, jormaechea commented on lib/helpers/structs.js
> +	filters: 'object?',
Y este lo podés hacer como

```js
filters: struct.optional(struct.dict(['string', filterStruct]))
```

Con eso (si funciona, no está chequeado), te ahorrás la lógica de recorrer los filtros y llamar al `filterStruct` a mano.

2020-02-06 18:48 UTC, jormaechea commented on lib/helpers/structs.js
> +const filterStruct = struct('string | number | array');
Por otro lado, no podrían ser objetos también?
Algo onda
```js
{
	filters: {
		dateCreated: {
			value: 'alguna fecha',
			type: 'greaterOrEqual'
		}
	}
}
```

2020-02-06 18:48 UTC, jormaechea commented on lib/api-export.js
> +		/* istanbul ignore else */
PD: cada vez que tenés que escribir un `istanbul ignore`, es señal de que escribiste código de más.

2020-02-06 18:48 UTC, jormaechea commented on package.json
> +    "superstruct": "0.6.1"
Mandale la 0.6.2 que es la que tenemos en todos lados

2020-02-10 13:51 UTC, jormaechea requested changes

2020-02-10 13:51 UTC, jormaechea commented on lib/controller-export.js
> +		const filename = `exports/${this.session.clientCode}/${this.userId}/${this.entity}-part${partNumber}.xlsx`;
Acá hay un temita. Si yo hago dos exports de la misma entidad, los archivos se sobreescriben.
Habría que meterle el ID del export, o un timestamp en el path para que no se pisen..

2020-02-10 13:51 UTC, jormaechea commented on lib/processed-listener.js
> +		return this.session.getSessionInstance(Mail).setTo(userEmail)
Este mail así como está no se va a mandar, porque no tiene body.

De todos modos, mejor mandarlo con un template, para queno dependa tanto el package.
Se quedarían los siguientes llamados:
- `setTemplateCode('export')` <-- El code del template a enviar.
- `setData({ ... })` <-- Esto se usa para reemplazar variables en el template
- `setEntity('export)` <-- La entidad es a la que se relaciona el mail, que debería ser export
- `setEntityId(exportId)` <-- Acá habría que meterle el ID del export que estás procesando

El `to`, `subject` y el `body` se definen en el template, y se reemplaza con le data.

Más arriba, agregá `userEmail` y `entity` en el objeto de `dataToSend`, así están disponibles para reemplazar en el template

2020-02-10 17:34 UTC, jormaechea approved these changes
:rocket:

2020-02-10 17:34 UTC, merged