Add export helper and controller formatters
janis-commerce/export pull request #7
Opened 2020-04-30 21:21 UTC by Alejandro-Gonzalez

**DESCRIPCIÓN DEL REQUERIMIENTO**

Se deben agregar dos clases  export-helpers y export-formatters.

**DESCRIPCIÓN DE LA SOLUCIÓN**

Se agregaron las dos clases y se testearion sus métodos.

2020-05-07 21:41 UTC, juanhapes requested changes

2020-05-07 21:41 UTC, juanhapes commented on lib/export-helpers/user-helper.js
> +		let users = await microServiceCall.list('id', 'user', { filters: { id: userIds } });
Al hacer este `list()` y no catchear, podes explotar si el servicio esta caido o devuelve un >`4xx`
Recomiendo usar `safeList()` y chequear el resultado.
Dejo la info entre la diferencia entre safe y no-safe: https://www.npmjs.com/package/@janiscommerce/microservice-call#no-safe-mode

2020-05-08 17:16 UTC, maguimarijuan requested changes

2020-05-08 17:16 UTC, maguimarijuan commented on README.md
> +class SomeConstroller extends ControllerExport {
"SomeController"

2020-05-08 17:16 UTC, maguimarijuan commented on README.md
> +class SomeConstroller extends ControllerExport {
Idem más arriba

2020-05-08 17:16 UTC, maguimarijuan commented on tests/api-export.js
> -					sandbox.assert.calledWithExactly(MsCall.prototype.get, 'id', 'user', 'get', null, null, { id: 2 });
Acá usaría calledOnceWithExactly

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/user-helper.js
> +		const microServiceCall = new MsCall(session);
Hay algo extraño con esta linea porque no veo en el paquete de microservice-call que pueda instanciarse de esta manera. No hay un constructor que reciba session. En tal caso, estarías usando una librería propia que wrappee esto. 
![image](https://user-images.githubusercontent.com/29028845/81426606-d1f1da00-912f-11ea-9f89-76a01fa80741.png)

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/user-helper.js
> +		const userIds = this.getIds();
Debería hacerse un control de si usersIds tiene efectivamente ids o si no devolver un objeto vacío y así evitar un llamado innecesario a JanisId. 

`
if(!userIds.length)
  return {};
`

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/user-helper.js
> +		const userIds = this.getIds();
Debe devolver un objeto vacío para evitar que el controlador trate de hacer algo como this.clients["unId"] y rompa horriblemente

2020-05-08 17:16 UTC, maguimarijuan commented on README.md
> +      this.entityData = await MyEntityHelper.getEntity(items, session)
Pondria get sólo así queda más polimórfico. Es decir que todos los helpers tengan el método get y les devuelva la entidad del nombre del helper. No sé si se entiende pero en JEF o JCAT ya está implementado de esta manera.

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/export-helper.js
> +
Yo agregaría el formatter de cuando tenes una lista de ids y queres una lista de ciertas propiedades de las entidades que corresponden a ese id, algo como este de sale channel de warehouse. 
``` js
/**
	 * Matches a list of sale-channel ids with a specified entity field
	 * Returns the matched list formatted into a single string
	 *
	 * @param {Array} saleChannelsIds The sale channels ids to filter
	 * @param {Object} saleChannels
	 * @param {string} field The sale channel field to format
	 * @returns
	 * @memberof ExportHelper
	 */
	static formatSaleChannel(saleChannelsIds, saleChannels, field) {

		return Object.values(saleChannels).reduce((formatted, { id, [field]: item }) => {

			if(!saleChannelsIds.includes(id))
				return formatted;
			return formatted ? `${formatted}, ${item}` : item;
		}, '');
	}
```

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/export-helper.js
> +
En este caso vos tenes un warehouse que tiene una lista de sale channels ids y queres que formatee eso como un solo array con los nombres y otro con los reference id. 
Así se usaría: 
``` js	
{
saleChannelsNames: saleChannel && this.saleChannels ? Formatter.formatSaleChannel(saleChannel, this.saleChannels, 'name') : null,
saleChannelsReferenceIds: saleChannel && this.saleChannels ? Formatter.formatSaleChannel(saleChannel, this.saleChannels, 'referenceId') : null,
}
```

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/export-helper.js
> +
Claramente pensaría un nombre más genérico como` Formatter.formatListBy(list, entities, fieldToFormat)`

2020-05-08 17:16 UTC, maguimarijuan commented on lib/export-helpers/export-helper.js
> +	/**
Acá está mal indentado

2020-05-08 17:16 UTC, maguimarijuan commented on lib/api-export.js
> +		const response = await this.session.getSessionInstance(MsCall).call('id', 'user', 'get', null, null, { id });
Claro acá usas this.session.getSessionInstance pero más abajo no :/ Así debería ser

2020-05-08 17:26 UTC, gastonpereyra commented on lib/export-helpers/user-helper.js
> +		const microServiceCall = new MsCall(session);
Estas en lo correcto no va a funcionar asi, para sessionar el MsCall lo corrector seria hacer algo asi:

```suggestion
		const microServiceCall = session.getSessionInstance(MsCall);
```

2020-05-08 19:21 UTC, gastonpereyra commented on README.md
> +    let entyData = await microServiceCall.safeList('service', 'entity', { filters: { id: entityIds } });
Guarda que aca puede pasar que `safeList` te devuelva `statusCode: 40X o 50X`, habria que chequear eso

2020-05-08 19:28 UTC, gastonpereyra commented on lib/export-helpers/user-helper.js
> +		let users = await microServiceCall.safeList('id', 'user', { filters: { id: userIds } });
Guarda que aca puede pasar que `safeList` te devuelva `statusCode: 40X o 50X`, habria que chequear eso y además, el resultado esta en `body`

2020-05-08 19:34 UTC, gastonpereyra commented on tests/export-helpers/user-helper.js
> +			sinon.stub(MsCall.prototype, 'safeList').resolves(Object.values(expectedData));
Como puse en otro comentario, el safeList, devuelve una respuesta asi;

```javascript
{
		headers: {
		 // The headers of the response.
		},
		statusCode: 200, // o 400 o 500
		statusMessage: 'Ok', // puede no haber
		body: [ 
			{
				id: 'id-1',
				name: 'Usuario 1'
			},
			// 1998 objects ...
			{
				id: 'ale-id',
				name: 'Ale'
			}
		]
	}
```

2020-05-08 19:36 UTC, gastonpereyra commented on lib/export-helpers/user-helper.js
> +		let users = await microServiceCall.safeList('id', 'user', { filters: { id: userIds } });
Esta es un modelo de respuesta:

```javascript
	{
		headers: {
		 // The headers of the response.
		},
		statusCode: 200, // o 400 o 500
		statusMessage: 'Ok', // puede no haber
		body: [ 
			{
				id: 'id-1',
				name: 'Usuario 1'
			},
			// 1998 objects ...
			{
				id: 'ale-id',
				name: 'Ale'
			}
		]
	}
```

2020-05-08 19:43 UTC, gastonpereyra commented
Otra cosa, si usas `safeList` para obtener los listados, talvés estaria bueno mantener la coherencia usando `safeCall` en vez de `call`.

2020-05-11 14:44 UTC, Alejandro-Gonzalez commented on lib/export-helpers/export-helper.js
> +
Agregué esto a export-formatters.js

2020-05-14 14:49 UTC, maguimarijuan approved these changes

2020-05-14 20:17 UTC, gastonpereyra approved these changes

2020-05-15 20:53 UTC, juanhapes commented on lib/export-formatters.js
> +
No queda mas fácil así?

```suggestion
return Object.values(entities)
			.filter(({ id }) => list.includes(id))
			.map(item => item[fieldToFormat])
			.join(', ');
```

2020-05-15 21:25 UTC, merged