Jcn 274 lambda instead of events
janis-commerce/export pull request #8
Opened 2020-05-29 19:24 UTC by maguimarijuan

**Link al ticket**
https://fizzmod.atlassian.net/browse/JCN-274
**Descripción del requerimiento**
Modificar el paquete de export a una nueva versión que use funciones lambda. Agregar los IAM statement permissions y las funciones lambda a un getter llamado `export-serverless`. Actualizar los paquetes. 
**Descripción de la solución**
Se agregó la funcion exportProcess. Se modificó la api post del paquete. Se eliminó todo lo referido a los listeners. Se actualizaron los paquetes. Se agregó el paquete @janiscommerce/superstruct. 
Se modificaron los estados a: 
- pending: Cuando se crea desde la API Create Export. Estado inicial.
- prossesed: Un export que se procesó correctamente.
- sent: Un export que se envió por mail. Estado final.
- sendingError: Un export que falló al enviar el mail. Estado final.

2020-06-01 12:59 UTC, gastonpereyra commented on README.md
> +* Create a generic Created Export Listener (:warning: deprecated since version 2.0.0)
Lo _removido_ lo sacaría de la lista de configuración y cuando esta termina agregaría un cartel con el :warning: que liste lo removido. Para no confundir

2020-06-01 13:04 UTC, gastonpereyra commented on README.md
>  ### ENV vars
Estaría bueno que aca también diga que se fijen en el package de Lambda sobre las configuraciones de las variables que ese package necesita

2020-06-01 13:08 UTC, gastonpereyra commented on README.md
> +In `path/to/root/[MS_PATH]/lambda/ExportProcess/index.js`.
Lo movería a la primera oración de esta "sección" , que es como esta en Controller.

2020-06-01 13:10 UTC, gastonpereyra commented on README.md
>  		return EventEmitter.emit({
Estos return me parece que quedaron mal identados, o github me los esta mostrando mal

2020-06-01 13:14 UTC, gastonpereyra commented on package.json
> +    "@janiscommerce/lambda": "^1.0.0",
Para mi, Lambda deberia ser una **peer dependency,** ya que necesitas de configuraciones externas a este package

2020-06-01 13:34 UTC, juanhapes commented on package.json
> +    "@janiscommerce/lambda": "^1.0.0",
No estoy de acuerdo, en la API POST Export usa explicitamente el package lambda, para mi va en `dependencies`

2020-06-01 14:10 UTC, gastonpereyra commented on README.md
> +## :warning: :skull: Deprecated
No le pondría Depreated sino Removed. Y no sé si dejaria toda la explicación ya que no se va a poder usar más.

2020-06-01 15:29 UTC, gastonpereyra commented on lib/helpers/validator.js
> +		sortDirection = this.validateSortDirection(sortDirection, sortBy);
Cambiaría el orden de las validaciones:

1- validar el sort, si no esta bien la "petición" ya no vale la pena validar el resto.
2- validar el model, si no esta no tiene sentido buscar el controller
3- validar el controller

2020-06-01 15:33 UTC, gastonpereyra commented on lib/helpers/validator.js
> +		return sortDirection;
Sugiero:

`return sortBy && !sortDirection ? 'asc' : sortDirectionsStruct(sortDirection);`

2020-06-01 15:48 UTC, gastonpereyra commented on lib/api-export.js
> +		return Invoker.clientCall('ExportProcess', this.session.clientCode, { id, ...dataSaved });
Aunque yo sé que es mas comodo usarlo asi, vamos a usar como un standard que el payload de los invoke no tengan un objeto tirado asi, por eso en el ticket te lo piden asi.

```suggestion
		return Invoker.clientCall('ExportProcess', this.session.clientCode, { exportDocument: { id, ...dataSaved } });
```

2020-06-01 15:52 UTC, gastonpereyra commented on lib/export-process.js
> +		const exportDocument = this.data;
Como mencione en el export-create, lo que llegaría como `exportDocument`
```suggestion
		const { exportDocument } = this.data;
```

2020-06-01 15:53 UTC, gastonpereyra commented on lib/export-process.js
> +		const exportDocument = this.data;
O incluso mejor:

`const { id, ...exportDocument } = this.data.exportDocument;`

2020-06-01 15:57 UTC, gastonpereyra commented on lib/export-process.js
> +			await this.exportModel.update({ status: this.statuses.sendingError }, { id, status: this.statuses.processed });
Falta agregar la prop `error`, explicando el error (como pide en el ticket)

2020-06-01 16:12 UTC, gastonpereyra requested changes
Deje un par de comentarios

2020-06-01 19:48 UTC, maguimarijuan commented on lib/helpers/validator.js
> +		return sortDirection;
El tema es si no hay ni sortDirection ni SortBy quiero que devuelva undefined. Lo contempla este ternario? :thinking:

2020-06-03 15:00 UTC, gastonpereyra commented on lib/export-process.js
> +		await this.exportModel.update({ status: this.statuses.processing }, { id, status: this.statuses.pending });
Aca falta chequear que update lo pudo actualizar o no.

`update` devuelve un `number` , 0 si no pudo actualizar o el numero de actualizados

2020-06-03 17:55 UTC, gastonpereyra commented on lib/export-process.js
> +	async updateStatus(id, newStatus, previousStatus) {
:bulb: Aca no haria que throwe.

Si el `update` devuelve `0` es que ya se proceso el dato (entonces ya cambio de estado en otro lado).

Simplemente dejo un logger y termino la ejecución

2020-06-04 14:32 UTC, gastonpereyra approved these changes
:+1:

2020-06-04 19:05 UTC, merged